name: 'Yarn Install'
description: 'Run yarn install'
inputs:
  skip-prisma-postinstall-generate:
   description: 'Avoid prisma to automatically generate schema on postinstall'
   required: false
   default: 'false'

runs:
  using: 'composite'
  steps:
   - name: Install dependencies
     shell: bash
     run: yarn install --immutable --inline-builds