name: 'Code Format'

on:
  push:
    branches:
      - main

jobs:
  build:
    name: build
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'

      - name: Get Yarn cache directory path
        id: yarn-config
        run: echo "::set-output name=dir::$(yarn config get cacheFolder)"

      - name: Read Yarn cache path
        run: |
          echo "Read Yarn cache path"
          echo "Path is ${{steps.yarn-config.outputs.DIR_PATH}}"
          echo "Finish Read"


